### ISSUE TITLE
Subscription payments Mobile

### ISSUE THREAD

**Issue by unxavi** [invertase/stripe-firebase-extensions#352]
# Feature request

- Extension name: firestore-stripe-payments

## Is your feature request related to a problem? Please describe.

When integrating this extension, the docs for the setup says `Subscription payments (web only)` why is that? what makes it hard to also integrate subscriptions for mobile devices? Could it be possible to work around this limitation?

On the recommended usage for the extension at the URL https://github.com/stripe/stripe-firebase-extensions/tree/next/firestore-stripe-payments 

It stays:

```If you're developing native mobile applications and you're selling digital products or services within your app, (e.g. subscriptions, in-game currencies, game levels, access to premium content, or unlocking a full version), you must use the app store's in-app purchase APIs. See [Apple's](https://developer.apple.com/app-store/review/guidelines/#payments) and [Google's](https://support.google.com/googleplay/android-developer/answer/9858738?hl=en&ref_topic=9857752) guidelines for more information.```

Which is not totally true

Apple Guidelines for example: https://developer.apple.com/app-store/review/guidelines/#payments

```3.1.3(d) Person-to-Person Services: If your app enables the purchase of real-time person-to-person services between two individuals (for example tutoring students, medical consultations, real estate tours, or fitness training), you may use purchase methods other than in-app purchase to collect those payments.```

```3.1.3(e) Goods and Services Outside of the App: If your app enables people to purchase physical goods or services that will be consumed outside of the app, you must use purchase methods other than in-app purchase to collect those payments, such as Apple Pay or traditional credit card entry.```

My current use case is a subscription  Person-to-Person that will be consumed outside of the app. So I'm affected by both rules and I *must* use a different purchase methods other than in-app purchase to be compliant.

So I don't understand why the extension limit this use cases.

## Describe the solution you'd like

I would like to use the extension to subscribe the users of a mobile app to stripe, since we are selling services outside of the app.

**Comment by jesus-mg-ios** [comment]
Hi:
@dackers86, Do you know when it is going to be develop. I think that it's a very interesting feature

**Comment by dackers86** [comment]
HI @jesus-mg-ios @unxavi.

I added the `enhancement` tag as I initially thought could require some development. However, could you provide a use case for this scenario?

The extension itself is simply use the `Stripe Api` at it's core. If this technique can be used through Stripe, I cannot a reason as to why we would limited through the extension?

Could this merely be a documentation update, or has anyone encountered a scenario where this type of request has not been possible?

**Comment by unxavi** [comment]
@dackers86 thanks for getting back to me.

## Use case

### Delivery Service

I want a user to be able to subscribe to a delivery service, the user pays a subscription fee and can order anything they want to be delivery, the service is consumed outside of the app, so on the AppStore guidelines you are asked to implement this with a payment system different than In App Purchases, if you do with IAP you are in violation of the guidelines, so Stripe mobile subscription is perfect for this use case.

`3.1.3(e) Goods and Services Outside of the App: If your app enables people to purchase physical goods or services that will be consumed outside of the app, you must use purchase methods other than in-app purchase to collect those payments, such as Apple Pay or traditional credit card entry.`

### Teaching

Another user case, you are music teacher which you have students that subscribe to your music classes through the application on the store, the classes are done through a video conference on a one to one class. One teacher - One student.

By the AppStore guidelines you could use other method different from In App Purchases, getting around the 30% fee of the AppStore  even if you make the video conference inside the app.

`3.1.3(d) Person-to-Person Services: If your app enables the purchase of real-time person-to-person services between two individuals (for example tutoring students, medical consultations, real estate tours, or fitness training), you may use purchase methods other than in-app purchase to collect those payments.`

In this use case if you decide not to deliver the lesson inside the app, but you use something like a link to zoom, then you are affected by the guideline **3.1.3(e) Goods and Services Outside of the App** and you should use another payment different of IAP to comply with the store rules.

## The extension API for subscriptions.

As you say, this extension uses the `Stripe API` and this extension docs says the following:

`Subscription payments (web only)`

The issue is that for web payments with the extension, you create a document on Firestore and the extension will give you back a `URL`where then you redirect a user to pay on the browser. This is good for a desktop browser experience and this API you can give to the extension the `price` id for the Stripe subscription.

On the other side, this extension for mobile, lets you make only one time payment, you write to Firestore the document with the following 

<img width="628" alt="imagen" src="https://user-images.githubusercontent.com/3817679/171132877-421ac8f1-1dee-4a0a-8574-09921de4a167.png">

And then the extension give you back the `paymentIntentClientSecret` and `ephemeralKeySecret` which then you can use inside the mobile app with the SwiftUI `PaymentSheet`  https://stripe.com/docs/payments/accept-a-payment?platform=ios&uikit-swiftui=swiftui

The `mode` `subscription` can't be use with the mobile in the extension, this will raise an error

https://github.com/stripe/stripe-firebase-extensions/blob/54a116d156232da10ebd6ebf8e96b4665a8fdeb1/firestore-stripe-payments/functions/src/index.ts#L286

### Wrapping up

This extension to work with subscription on a mobile app is incomplete and non functional. We need to be able to use the `price` id param like for the web, but instead of getting back an URL, we need to get back the `ephemeralKeySecret` to be able to use it with the SwiftUI object `PaymentSheet` from stripe. 

To be able to accomplish this, we should implement the correct `Stripe API` to handle this use case, which is possible on this extension.

Example Stripe API Call.

```
 const subscription = await stripe.subscriptions.create({
      customer: customerId,
      items: [{ plan: priceId],
      payment_behavior: "default_incomplete",
      expand: ["latest_invoice.payment_intent"],
      payment_settings: {
        save_default_payment_method: "on_subscription",
      },
      metadata: {
        firebaseUserUID: userUid,
      },
    });
```

@dackers86  I think this post is already long enough, if you have any doubts or comments, could you get back? At least to clear any doubt.

Do you think we could implement this? Stripe is great for some use cases on mobile where we can't use IAP or have the option of not using it, and yet this extension does not cover this uses cases.

**Comment by unxavi** [comment]
@dackers86 any doubt?

**Comment by dackers86** [comment]
Hi @unxavi Thanks for the awesome feedback.

We will look at producing an investigative PR based on the above!

**Comment by var2611** [comment]
Waiting for update.

**Comment by SohelIslamImran** [comment]
Waiting. @dackers86 Please merge your PR

**Comment by rahulsain** [comment]
PR merged, now waiting for official integration docs

**Comment by rahulsain** [comment]
is official docs now updated, for how to use mobile subscription?

**Comment by dackers86** [comment]
@rahulsain Thanks, you're correct, documentation needs to be added.

I'll close this issue as the feature has been added. Please track this new [issue](https://github.com/invertase/stripe-firebase-extensions/issues/new?assignees=&labels=&projects=&template=2.Feature_request.md) for documentation updates.
