### ISSUE TITLE
i can't get my products in firedatabase

### ISSUE THREAD

**Issue by santoshswain1416** [invertase/stripe-firebase-extensions#435]
# Bug report

- Extension name: [e.g. `firestore-stripe-payments`]

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by dackers86** [comment]
Closing due to lack of description/details.
