### ISSUE TITLE
Add support for "payment_method_collection"

### ISSUE THREAD

**Issue by chilledtonic** [invertase/stripe-firebase-extensions#476]
# Feature request

- Extension name: `firestore-stripe-payments`

## Is your feature request related to a problem? Please describe.

Currently, if a checkout link is generated where a user can enter a promotion code for a 100% discount, they are still forced to enter payment information to complete the checkout.

A recent update to the API allows "payment_method_collection" to be set to "if_required", which allows customers to enter payment details in their profile instead of before the trial starts.

## Describe the solution you'd like

I'd like to be able to pass this request to the DB the same way you pass other requirements to the customers table. ie.
```javascript
 collection(db, `customers/${auth.currentUser.uid}/checkout_sessions`),
        {
          automatic_tax: true,
          allow_promotion_codes: true,
          price: payload.payload,
          payment_method_collection: "if_required", // right here
          success_url: window.location.origin + "/checkout",
          cancel_url: window.location.origin + "/dashboard",
        }
```

## Describe alternatives you've considered

There appears to be no alternatives for passing this flag via this firebase plugin.

**Comment by ditmarh** [comment]
I have the same issue. I want to offer my users a 30-day free trial without the need to enter credit card information.  The trial works; however, the user is required to enter their credit card details despite using: payment_method_collection: 'if_required'

**Comment by AnthonyNahas** [comment]
I am facing the same issue.. 

like @chilledtonic  and @ditmarh, I want to offer my users 30 days free trials of the PRO Plan without entering payments information.

It seems that supporting this

```ts
payment_method_collection: "if_required"
```

in firebase extension could will only solve the problem!

**Comment by avelow** [comment]
I am facing the same issue too.

**Comment by camilleganzin** [comment]
Same here! Would be so helpful

**Comment by mattlrobinson7** [comment]
Same here. Very important for my business to offer free trials with no credit card required.

**Comment by scole954387** [comment]
Any updates on this? I admit I am disappointed in the lack of updates of the stripe extension lately. I've been told by some stripe people on discord/email that this extension is basically left to die which is very unfortunate.

**Comment by chilledtonic** [comment]
This has been corrected in later versions.
