### ISSUE TITLE
Inadequate

### ISSUE THREAD

**Issue by TheWizardofWikacy** [invertase/stripe-firebase-extensions#530]
These functions are highly inadequate, and it seems like google is tricking people into making an inadequate payment flow.  The functions do not allow for line items, e.g., as in a shopping cart, connect products, etc.  And they do not follow stripes convention of setupIntent.

**Comment by dackers86** [comment]
Hi @TheWizardofWikacy 

Stripe has now transferred this repository to Invertase, please https://github.com/invertase/stripe-firebase-extensions/issues/542.

We will be prioritising and triaging upcoming features and bugs

**Comment by dackers86** [comment]
Closing this issue for now.

If any of the above features/issues are needed, please file a separate issue or feature request so that we add them to our backlog
