### ISSUE TITLE
Transfer repo to Invertase

### ISSUE THREAD

**Issue by paulasjes-stripe** [invertase/stripe-firebase-extensions#542]
Reposting for visibility from https://github.com/stripe/stripe-firebase-extensions/issues/524#issuecomment-1671603107 

We've worked with the Firebase team to identify a new owner, Invertase, to take over maintenance of this extension and be its long-term steward.

[Invertase](https://github.com/invertase) is a seasoned developer shop that has worked closely with the Firebase team and actively maintains several other Firebase extensions. The Invertase team is committed to addressing this extension’s existing issues and providing long-term maintenance.

Note that once the transfer is complete, you’ll have to uninstall the [stripe/firestore-stripe-payments](https://extensions.dev/extensions/stripe/firestore-stripe-payments) extension from the Firebase Extension Hub and install the Invertase version to get any updates. Once the Invertase version is available, we’ll follow up in this issue and update the readme.

Thank you all for your patience, to @ksnyder for bringing this to our attention, and @lucasyvas for their willingness to support the community. We hope you continue participating in Invertase's upcoming update and help push this extension forward. We’re here if you have any questions or concerns.

**Comment by paulasjes-stripe** [comment]
This is now complete! Thank you everyone for your patience and huge thanks for Invertase for taking on this repo!

**Comment by TheRedSpy15** [comment]
npm is unable to find the package when installing with:

```
npm install @invertase/firestore-stripe-payments@latest
```
