### ISSUE TITLE
Update to node 18 or 20 -> Node 14 will be deprecated on january 31

### ISSUE THREAD

**Issue by Jidzo1** [invertase/stripe-firebase-extensions#583]
Hello,

Can you update the Google Cloud functions used with this extension to the latest node version?
So that it won't get deprecated on January 31. (Node 14 is being removed by Google).
See screenshot:

![node14](https://github.com/invertase/stripe-firebase-extensions/assets/102975203/c0e026e6-d6a2-4772-94f4-de593d27f4d5)

Thanks,

**Comment by matehubert** [comment]
Hello, I have the same question, what csn we do? There will be an update?

**Comment by tgangso** [comment]
Any update?

**Comment by xaoo** [comment]
This one is pretty important, the extension will be obsolete in a very short time.
Is this being addressed?

**Comment by print-VarunSharma** [comment]
I second all of the comments that have been left here! We'll need an update from the team please! 🙏🏽

**Comment by Jidzo1** [comment]
Update:
I contacted the Invertase team on their discord channel and they told me they are gonna update this this week.
See screenshot

![image](https://github.com/invertase/stripe-firebase-extensions/assets/102975203/c57b8be3-d47a-48b7-b188-8c26ce3f9fe9)

I will close this issue when done

**Comment by print-VarunSharma** [comment]
> Update: I contacted the Invertase team on their discord channel and they told me they are gonna update this this week. See screenshot
> 
> ![image](https://private-user-images.githubusercontent.com/102975203/291907268-c57b8be3-d47a-48b7-b188-8c26ce3f9fe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMDgwOTksIm5iZiI6MTcwMzEwNzc5OSwicGF0aCI6Ii8xMDI5NzUyMDMvMjkxOTA3MjY4LWM1N2I4YmUzLWQ0N2EtNDhiNy1iMTg4LThjMjZjZTNmOWZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQyMTI5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDMxMTk4ODQwZmU5MTE3YzI0NzdkMDgyNTA3NTIwYjdiODUyYmEwYTVjY2YwOGRjMTcyYzNhMDdlODVkMjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m_LnRPYlUbowXxBKoV-CnPqA8HP8-uCxkUbf1AwCARA)
> 
> I will close this issue when done

This is fantastic news. Thank you for updating the community about this!  Keep us in the loop 🙏🏽 
![image](https://github.com/invertase/stripe-firebase-extensions/assets/62218708/b8697f26-8126-45ad-9ac5-6b490a0b2150)

**Comment by xaoo** [comment]
@pr-Mais 

Thanks for the update, already upgraded.

But I saw there are still two functions missing the update:
![image](https://github.com/invertase/stripe-firebase-extensions/assets/948710/12b8805e-3667-4b0a-a6c4-2ff7defd3be0)

Are this in the next PR or?

Thank you

**Comment by pr-Mais** [comment]
@xaoo oh that's right, sorry I missed those, drafting another update now.

**Comment by pr-Mais** [comment]
Version `0.3.8` supports node18 now, closing as resolved.

**Comment by print-VarunSharma** [comment]
> Version `0.3.8` supports node18 now, closing as resolved.

AMAZING! 🚀  Thanks Invertase team! ❤️

**Comment by bakermanbrian** [comment]
@pr-Mais can you update the extension to 0.3.8 in the Firebase extension marketplace:
https://extensions.dev/extensions/stripe/firestore-stripe-payments

**Comment by pr-Mais** [comment]
The extension has been moved to the Invertase publisher, hence the correct link is: https://extensions.dev/extensions/invertase/firestore-stripe-payments, the one you linked is deprecated.

**Comment by jensbuehl** [comment]
I ran into the same issue after enabling the extension today. 
Seems that some functions are still behind?

![image](https://github.com/user-attachments/assets/68ac44ce-61f0-49db-a832-aed4593922b8)

**Comment by loganvaz** [comment]
Has this been fixed?
