### ISSUE TITLE
createCustomer is not triggered

### ISSUE THREAD

**Issue by miloops** [invertase/stripe-firebase-extensions#585]
# Bug report

- Extension name: firestore-stripe-payments

## Describe the bug

Stripe customer are created after a Firebase user is created.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a Firebase user
2. No Stripe customer is created
3. createCustomer function is not called

## Expected behavior

When a Firebase user is created `createCustomer` function should be triggered

**Comment by ozair-dev** [comment]
Hi @miloops !
I'm also facing this bug. Did it get fixed or something?, since you've closed the issue!
