### ISSUE TITLE
createPortalLink success_url

### ISSUE THREAD

**Issue by msm1227** [invertase/stripe-firebase-extensions#586]
I am wondering if it is possible to redirect a user to a success_url on my own site when they complete the checkout process in the stripe customer portal. 

An example is if we have an existing customer who is on our free plan in stripe and they decide to upgrade to a pro plan. If they upgrade to pro and complete the checkout process is there a way to redirect them back to a specific page on my site?

I have that working for new customers who signup as pro and completes the checkout process at that time but not for ones that are free and want to upgrade at a later time. 

This is my current code:

```
let proThankYou = "https://site.com/thank-you-pro.html";

const handleMangeLink = async (user) => {
    const functions = getFunctions(app, 'us-central1');
                    const createPortalLink = httpsCallable(
                    functions, 
                    'ext-firestore-stripe-payments-createPortalLink');
                    createPortalLink({
                        returnUrl: window.location.origin,
                        success_url: proThankYou,
                    })
                    .then((result) => {
                        manage_url = result.data.url;
                    }).catch((error) => {
                        const errorCode = error.code;
                        const errorMessage = error.message;
                        console.log(errorCode + errorMessage)
                    });
}
```

Thanks!

**Comment by jauntybrain** [comment]
Hi @msm1227, thanks for reporting this issue!

Unfortunately, since `createPortalLink` opens the Billing Portal and not a Checkout Session, you can only pass a `return_url` parameter as per [Stripe documentation](https://stripe.com/docs/api/customer_portal/sessions/create).
