### ISSUE TITLE
Support trial — there's no longer the legacy option for setting a trial in Stripe

### ISSUE THREAD

**Issue by matheusbaumgart** [invertase/stripe-firebase-extensions#599]
@jsteele-stripe  There's no longer the legacy option for setting a trial in Stripe. So `trial_from_plan` workaround is no longer valid.

_Originally posted by @alex-i0 in https://github.com/invertase/stripe-firebase-extensions/issues/274#issuecomment-1875938597_

**Comment by matheusbaumgart** [comment]
The only way to add this now is to go through the Billings page and creating the product there. Even then, as stated here, it's no longer supported on Checkout

<img width="369" alt="image" src="https://github.com/invertase/stripe-firebase-extensions/assets/4028897/6814d70a-80ee-464c-aac0-ee4a83e8e9be">

**Comment by LimarenkoDenis** [comment]
Any updates?

I see the only solution now - is to create a custom implementation (firebase function that create stripe checkout session with `subscription_data[trial_period_days]`), right?
