### ISSUE TITLE
Upgrade node version >= 18

### ISSUE THREAD

**Issue by AlexJetplan** [invertase/stripe-firebase-extensions#621]
# Feature request
Hey!

Stripe version 14 has been deprecated for a while now and firebase is taking action. They sent out an email asking us to upgrade our functions to a supported version (>=18) otherwise we won't be able to deploy these functions anymore.

Are there any plans to upgrade to a higher version of node or will firebase extension support just stop from your end?

**Comment by AlexJetplan** [comment]
Just saw that this is a duplicate of https://github.com/invertase/stripe-firebase-extensions/issues/583, closing, my bad.

**Comment by jensbuehl** [comment]
Do you have further insights? In the other thread it was discussed, but I still see the outdated node runtime.
![image](https://github.com/user-attachments/assets/e274fc3a-0ebf-4aa6-af91-8d5c4ee9632a)

**Comment by AlexJetplan** [comment]
> EDIT: Firebase was highlighting the deprecated extension. Just search for the extension and use the one from the new publisher. Thanks for the hint in this thread!

That's right. There is a new team that has taken over maintenance, their name is Inveratse and this is the extension: https://extensions.dev/extensions/invertase/firestore-stripe-payments
