### ISSUE TITLE
Subscriptions sub collection not being created in Firebase

### ISSUE THREAD

**Issue by 884k** [invertase/stripe-firebase-extensions#646]
Describe the bug
When a user successfully pays for their subscription, only a 'checkout_sessions' and 'payment' subcollection is created in Firestore. There is supposed to be a 'subscriptions' subcollection that is created when a user succesfully pays for a subscription. 

To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:

Follow[ instructions provided](https://invertase.io/blog/firebase-stripe-extension-with-flutter-web#review-access-granted-to-stripe-extension)
Log in and pay for subscription
Check Firestore
<img width="574" alt="image" src="https://github.com/user-attachments/assets/dfc656c7-2e13-45a9-9846-c15950fb4159">

Additional Information
	•	I have already tried the solution mentioned in [issue #630](https://github.com/invertase/stripe-firebase-extensions/issues/630).
	•	Webhook events and logs indicate that the process completes successfully.
	•	This was executed in Test Mode.

**Comment by strivekiley** [comment]
@884k how did you end up fixing this?  I have the same thing happening.

**Comment by 884k** [comment]
@strivekiley The solution was very simple.
All I had to do was scroll through the area where the checkout_session and payment were…

The subscription had already been created—I just couldn’t see it.

**Comment by strivekiley** [comment]
@884k Welp, that's embarrassing!  It'd be nice if there was _some_ sort of indication that there's more to see.  

<img width="622" alt="Image" src="https://github.com/user-attachments/assets/3f255a99-cba7-431d-be3b-3f55d4504b62" />

Anyway, thank you for pointing out the obvious!
